name: torch_mobile
description: A Flutter plugin for inference of Pytorch models. Supports image classification on Android.
version: 0.0.2
author: Julien Marichez <julien.marichez@hosa.io>
homepage: https://github.com/jmarichez/flutter_torch_mobile

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.3.1
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.hosa.torch_mobile
    pluginClass: TorchMobilePlugin
